const definitions = [
    ["start", "Start the bot guide", "General", "user", "/start"], ["find", "Save a student ID", "Registration", "user", "/find <MSSV>"],
    ["dangky", "Enable schedule notifications", "Notifications", "user", "/dangky [MSSV] [hh:mm]"], ["danhsachdangky", "List saved notification times", "Notifications", "user", "/danhsachdangky"],
    ["suadangky", "Update a notification time", "Notifications", "user", "/suadangky #ID <hh:mm>"], ["xoadangky", "Remove a notification time", "Notifications", "user", "/xoadangky #ID"],
    ["lich", "View today's schedule", "Schedule", "user", "/lich [MSSV]"], ["lichtuan", "View the weekly schedule", "Schedule", "user", "/lichtuan [MSSV]"], ["lichthi", "View exam schedule", "Schedule", "user", "/lichthi [MSSV]"], ["lichgv", "View a teacher schedule", "Schedule", "user", "/lichgv <teacher>"], ["phongtrong", "Find empty rooms", "Schedule", "user", "/phongtrong [campus]"],
    ["ai", "Ask the schedule assistant", "AI", "user", "/ai <question>"], ["batnhaclich", "Enable class-start reminders", "Notifications", "user", "/batnhaclich"], ["tatnhaclich", "Disable class-start reminders", "Notifications", "user", "/tatnhaclich"], ["trangthainhaclich", "View reminder status", "Notifications", "user", "/trangthainhaclich"], ["huythongbao", "Disable schedule notifications", "Notifications", "user", "/huythongbao"], ["sinhnhat", "Ask the birthday assistant", "Birthday", "user", "/sinhnhat <question>"], ["myid", "Show your account ID", "General", "user", "/myid"], ["lichtruc", "View duty schedule", "Duty", "user", "/lichtruc"], ["danhsachlichtruc", "List duty assignments", "Duty", "user", "/danhsachlichtruc"], ["dangkylich", "Enable duty notifications", "Duty", "user", "/dangkylich"], ["huydangkylich", "Disable duty notifications", "Duty", "user", "/huydangkylich"], ["help", "Show available user commands", "General", "user", "/help"], ["help411", "Show duty commands", "Duty", "user", "/help411"],
    ["blockbot", "Block bot access", "Administration", "owner", "/blockbot <target>"], ["unblockbot", "Unblock bot access", "Administration", "owner", "/unblockbot <target>"], ["blockai", "Block AI access", "Administration", "owner", "/blockai <target>"], ["unblockai", "Unblock AI access", "Administration", "owner", "/unblockai <target>"], ["allowbot", "Allow bot access", "Administration", "owner", "/allowbot <target>"], ["unallowbot", "Remove bot allowlist access", "Administration", "owner", "/unallowbot <target>"], ["allowai", "Allow AI access", "Administration", "owner", "/allowai <target>"], ["unallowai", "Remove AI allowlist access", "Administration", "owner", "/unallowai <target>"], ["accessmode", "Set access mode", "Administration", "owner", "/accessmode <bot|ai> <mode>"], ["accesslist", "Show access lists", "Administration", "owner", "/accesslist"], ["quanlychat", "List and filter chats", "Administration", "owner", "/quanlychat [filter] [page]"], ["thongtinch", "Show chat details", "Administration", "owner", "/thongtinch <chatId>"], ["vohieuchat", "Disable a chat", "Administration", "owner", "/vohieuchat <chatId>"], ["kichhoatchat", "Reactivate a chat", "Administration", "owner", "/kichhoatchat <chatId>"], ["thuchatchat", "Soft-remove a chat", "Administration", "owner", "/thuchatchat <chatId>"], ["xoachat", "Delete a chat", "Administration", "owner", "/xoachat <chatId>"], ["chatfeature", "Override a chat feature", "Administration", "owner", "/chatfeature <chatId> <feature> <on|off>"], ["thongbao", "Send an announcement", "Administration", "owner", "/thongbao <message>"], ["themlichtruc", "Add duty schedules", "Duty", "owner", "/themlichtruc <input>"], ["sualichtruc", "Edit a duty schedule", "Duty", "owner", "/sualichtruc <input>"], ["xoalichtruc", "Delete a duty schedule", "Duty", "owner", "/xoalichtruc <date>"], ["danhsach", "List birthday questions", "Birthday", "owner", "/danhsach <year>"], ["them", "Add a birthday question", "Birthday", "owner", "/them <question>"], ["sua", "Edit a birthday question", "Birthday", "owner", "/sua <id> <question>"], ["xoa", "Delete a birthday question", "Birthday", "owner", "/xoa <id>"], ["traloi", "Answer a birthday question", "Birthday", "owner", "/traloi <id> <answer>"], ["congbo", "Publish birthday answers", "Birthday", "owner", "/congbo <year>"], ["test6h", "Test schedule delivery", "Diagnostics", "owner", "/test6h"], ["test6hlichtruc", "Test duty delivery", "Diagnostics", "owner", "/test6hlichtruc"], ["helpadmin", "Show admin commands", "Administration", "owner", "/helpadmin"], ["time", "Show Vietnam time", "General", "user", "/time"]
].map(([name, description, category, permission, usage]) => ({ name: `/${name}`, aliases: [], description, category, permission, usage, examples: [usage], arguments: [] }));

function getCommandRegistry() { return definitions.map((command) => ({ ...command, arguments: command.arguments.map((argument) => ({ ...argument })) })); }
function findCommand(name) { const needle = String(name || "").replace(/^\//, "").toLowerCase(); return definitions.find((command) => command.name.slice(1) === needle || command.aliases.includes(needle)) || null; }

module.exports = { findCommand, getCommandRegistry };
