const base = new URL(document.baseURI).pathname.replace(/\/$/, "");
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[char]));
let dashboard = null;
let notifications = null;
let logs = null;
let settings = null;

async function api(path, options = {}) {
  const response = await fetch(`${base}${path}`, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(options.headers || {}) }, ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) { const error = new Error(data.error || "Request failed"); error.status = response.status; throw error; }
  return data;
}

function showAuthenticated(authenticated) { $("#loginView").classList.toggle("hidden", authenticated); $("#dashboardView").classList.toggle("hidden", !authenticated); $("#logoutButton").classList.toggle("hidden", !authenticated); }
function formatDate(value) { if (!value) return "-"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : date.toLocaleString(); }
function statusClass(status) { return `status status-${escapeHtml(status || "unknown")}`; }

function renderAdminSettings() {
  const admins = settings?.admins || [];
  $("#adminSettingsList").innerHTML = admins.map((admin) => `<div class="stack-item"><div class="stack-title">${escapeHtml(admin.displayName || admin.userId || admin.chatId)}</div><div class="stack-meta">User: ${escapeHtml(admin.userId || "-")} · Chat: ${escapeHtml(admin.chatId || "-")}</div><button class="mini-button" data-remove-admin="${escapeHtml(admin.userId || admin.chatId)}">Remove</button></div>`).join("") || `<p class="muted">No dashboard admin identity configured yet.</p>`;
  document.querySelectorAll("[data-remove-admin]").forEach((button) => button.addEventListener("click", async () => { await api(`/api/admin/settings/admins?id=${encodeURIComponent(button.dataset.removeAdmin)}`, { method: "DELETE" }); await loadDashboard(); }));
}

function render() {
  const chats = dashboard.chats;
  $("#metricGrid").innerHTML = [["Registered chats", chats.total, `${chats.users} users · ${chats.groups} groups`], ["Active chats", chats.active, "Eligible for delivery"], ["Invalid / unreachable", chats.inactive, "Requires review"], ["Schedule subscriptions", dashboard.notifications.activeSubscriptions, "Currently enabled"], ["Failed deliveries", dashboard.notifications.failedDeliveries, "Recorded in chat history"]].map(([label, value, note]) => `<article class="metric"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></article>`).join("");
  const status = $("#statusFilter").value; const type = $("#typeFilter").value;
  api(`/api/admin/chats?status=${encodeURIComponent(status)}&type=${encodeURIComponent(type)}`).then(({ chats: filtered }) => {
    $("#chatRows").innerHTML = filtered.map((chat) => `<tr><td><div class="chat-name">${escapeHtml(chat.displayName || "Unnamed chat")}</div><div class="chat-id">Chat: ${escapeHtml(chat.chatId)}<br>User: ${escapeHtml(chat.userId || "-")}</div></td><td>${escapeHtml(chat.chatType || "unknown")}</td><td><span class="${statusClass(chat.status)}">${escapeHtml(chat.status)}</span></td><td>${escapeHtml(formatDate(chat.lastSuccessfulDeliveryAt))}</td><td>${escapeHtml(chat.lastError ? `${chat.lastError.status || chat.lastError.code || "ERR"} ${chat.lastError.message}` : "-")}</td><td><button class="mini-button" data-chat="${escapeHtml(chat.chatId)}">Details</button></td></tr>`).join("") || `<tr><td colspan="6" class="muted">No chats match this filter.</td></tr>`;
    document.querySelectorAll("[data-chat]").forEach((button) => button.addEventListener("click", () => openDetails(button.dataset.chat)));
  });
  const systemErrors = (logs?.system || []).slice(0, 8).map((event) => `<div class="stack-item"><div class="stack-title">${escapeHtml(event.level)} · System</div><div class="stack-meta">${escapeHtml(event.message)}</div><div class="stack-meta">${escapeHtml(formatDate(event.at))}</div></div>`);
  const deliveryErrors = (dashboard.recentErrors || []).slice(0, 8).map((chat) => `<div class="stack-item"><div class="stack-title">${escapeHtml(chat.displayName || chat.chatId)}</div><div class="stack-meta">${escapeHtml(chat.lastError?.message || "Unknown error")}</div><div class="stack-meta">${escapeHtml(formatDate(chat.lastError?.at))}</div></div>`);
  $("#errorList").innerHTML = [...systemErrors, ...deliveryErrors].slice(0, 10).join("") || `<p class="muted">No recent errors.</p>`;
  $("#auditList").innerHTML = (dashboard.audit || []).map((event) => `<div class="stack-item"><div class="stack-title">${escapeHtml(event.action)}</div><div class="stack-meta">${escapeHtml(event.admin)} · ${escapeHtml(formatDate(event.at))}</div></div>`).join("") || `<p class="muted">No admin activity yet.</p>`;
  const scheduleRows = (notifications?.schedule || []).slice(0, 12).map((item) => `<div class="stack-item"><div class="stack-title">${escapeHtml(item.userDisplayName || item.studentName || item.chatId)}</div><div class="stack-meta">Study schedule · ${escapeHtml((item.notificationTimes || []).map((entry) => entry.time).join(", ") || "06:00")} · ${escapeHtml(item.chatId)}</div></div>`);
  const dutyRows = (notifications?.duty || []).slice(0, 8).map((item) => `<div class="stack-item"><div class="stack-title">${escapeHtml(item.chatTitle || item.chatId)}</div><div class="stack-meta">Room 411 duty · 06:00 daily</div></div>`);
  $("#notificationList").innerHTML = [...scheduleRows, ...dutyRows].join("") || `<p class="muted">No active notification subscriptions.</p>`;
  $("#healthPill").textContent = `${dashboard.bot.status} · ${dashboard.bot.health}`;
  renderAdminSettings();
}

async function loadDashboard() { [dashboard, notifications, logs, settings] = await Promise.all([api("/api/admin/dashboard"), api("/api/admin/notifications"), api("/api/admin/logs"), api("/api/admin/settings")]); render(); }

async function openDetails(chatId) {
  const data = await api(`/api/admin/chats/${encodeURIComponent(chatId)}`); const chat = data.chat;
  $("#dialogTitle").textContent = chat.displayName || chat.chatId;
  const error = chat.lastError ? `${chat.lastError.status || chat.lastError.code || "ERR"} ${chat.lastError.message}` : "-";
  const overrides = chat.notificationOverrides || {};
  const history = (data.deliveryHistory || []).slice(0, 12).map((item) => `<div class="stack-item"><div class="stack-title">${escapeHtml(item.result)} · ${escapeHtml(item.feature || item.operation || "delivery")}</div><div class="stack-meta">${escapeHtml(item.message || "Delivered successfully")}</div><div class="stack-meta">${escapeHtml(formatDate(item.at))}</div></div>`).join("") || `<p class="muted">No delivery history recorded yet.</p>`;
  $("#dialogBody").innerHTML = `<form id="chatMetadataForm"><div class="detail-grid"><label>Chat ID<input value="${escapeHtml(chat.chatId)}" disabled /></label><label>User ID<input name="userId" value="${escapeHtml(chat.userId || "")}" /></label><label>Display name<input name="displayName" value="${escapeHtml(chat.displayName || "")}" /></label><label>Type<select name="chatType"><option value="private" ${chat.chatType === "private" ? "selected" : ""}>User</option><option value="group" ${chat.chatType === "group" ? "selected" : ""}>Group</option><option value="unknown" ${chat.chatType === "unknown" ? "selected" : ""}>Unknown</option></select></label><div class="detail"><label>Status</label><p class="${statusClass(chat.status)}">${escapeHtml(chat.status)}</p></div><div class="detail"><label>Last inbound interaction</label><p>${escapeHtml(formatDate(chat.lastInboundInteractionAt))}</p></div><div class="detail"><label>Last successful delivery</label><p>${escapeHtml(formatDate(chat.lastSuccessfulDeliveryAt))}</p></div><div class="detail"><label>Latest error</label><p>${escapeHtml(error)}</p></div></div><button class="primary" type="submit">Save details</button></form><div class="panel-heading" style="margin-top:18px"><strong>Admin actions</strong></div><div class="filters action-wrap"><button class="mini-button" data-action="active">Reactivate</button><button class="mini-button" data-action="disabled">Disable</button><button class="mini-button" data-action="removed">Soft remove</button><button class="mini-button" data-make-admin="1">Make admin</button><button class="mini-button danger" data-hard-delete="1">Delete permanently</button><button class="mini-button" data-retry="1">Retry delivery</button></div><div class="panel-heading" style="margin-top:18px"><strong>Notification features</strong></div><div class="stack">${["schedule", "duty", "birthday", "broadcast"].map((feature) => `<div class="stack-item"><div class="stack-title">${feature}</div><div class="stack-meta">Override: ${overrides[feature] == null ? "automatic" : overrides[feature] ? "enabled" : "disabled"}</div><div class="filters" style="margin-top:7px"><button class="mini-button" data-feature="${feature}" data-enabled="true">Enable</button><button class="mini-button" data-feature="${feature}" data-enabled="false">Disable</button><button class="mini-button" data-feature="${feature}" data-enabled="auto">Automatic</button></div></div>`).join("")}</div><div class="panel-heading" style="margin-top:18px"><strong>Delivery history</strong></div><div class="stack">${history}</div>`;
  if (!$("#detailDialog").open) $("#detailDialog").showModal();
  document.querySelectorAll("[data-action]").forEach((button) => button.addEventListener("click", async () => { await api(`/api/admin/chats/${encodeURIComponent(chatId)}`, { method: "PATCH", body: JSON.stringify({ action: "status", status: button.dataset.action, reason: `dashboard_${button.dataset.action}` }) }); $("#detailDialog").close(); await loadDashboard(); }));
  document.querySelectorAll("[data-retry]").forEach((button) => button.addEventListener("click", async () => { button.disabled = true; try { await api(`/api/admin/chats/${encodeURIComponent(chatId)}/retry`, { method: "POST" }); $("#detailDialog").close(); await loadDashboard(); } catch (retryError) { button.disabled = false; alert(retryError.message); } }));
  document.querySelectorAll("[data-feature]").forEach((button) => button.addEventListener("click", async () => { const enabled = button.dataset.enabled === "auto" ? null : button.dataset.enabled === "true"; await api(`/api/admin/chats/${encodeURIComponent(chatId)}`, { method: "PATCH", body: JSON.stringify({ action: "feature", feature: button.dataset.feature, enabled }) }); await openDetails(chatId); }));
  $("#chatMetadataForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); await api(`/api/admin/chats/${encodeURIComponent(chatId)}`, { method: "PATCH", body: JSON.stringify({ action: "metadata", userId: form.get("userId"), displayName: form.get("displayName"), chatType: form.get("chatType") }) }); $("#detailDialog").close(); await loadDashboard(); });
  document.querySelectorAll("[data-make-admin]").forEach((button) => button.addEventListener("click", async () => { await api("/api/admin/settings/admins", { method: "POST", body: JSON.stringify({ userId: chat.userId || "", chatId: chat.chatId, displayName: chat.displayName || chat.chatId }) }); await loadDashboard(); await openDetails(chatId); }));
  document.querySelectorAll("[data-hard-delete]").forEach((button) => button.addEventListener("click", async () => { if (!confirm(`Permanently delete chat ${chatId}? History cannot be restored.`)) return; await api(`/api/admin/chats/${encodeURIComponent(chatId)}?hard=1`, { method: "DELETE" }); $("#detailDialog").close(); await loadDashboard(); }));
}

$("#loginForm").addEventListener("submit", async (event) => { event.preventDefault(); $("#loginError").textContent = ""; const form = new FormData(event.currentTarget); try { await api("/api/admin/auth/login", { method: "POST", body: JSON.stringify({ username: form.get("username"), password: form.get("password") }) }); showAuthenticated(true); await loadDashboard(); } catch (error) { $("#loginError").textContent = error.message; } });
$("#logoutButton").addEventListener("click", async () => { await api("/api/admin/auth/logout", { method: "POST" }); showAuthenticated(false); });
$("#refreshButton").addEventListener("click", loadDashboard); $("#statusFilter").addEventListener("change", render); $("#typeFilter").addEventListener("change", render); $("#closeDialog").addEventListener("click", () => $("#detailDialog").close());
$("#chatForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api("/api/admin/chats", { method: "POST", body: JSON.stringify(Object.fromEntries(form.entries())) }); event.currentTarget.reset(); $("#chatFormMessage").textContent = "Saved."; await loadDashboard(); } catch (error) { $("#chatFormMessage").textContent = error.message; } });
$("#adminForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api("/api/admin/settings/admins", { method: "POST", body: JSON.stringify(Object.fromEntries(form.entries())) }); event.currentTarget.reset(); $("#adminFormMessage").textContent = "Saved."; await loadDashboard(); } catch (error) { $("#adminFormMessage").textContent = error.message; } });
$("#commandForm").addEventListener("submit", async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await api("/api/admin/commands", { method: "POST", body: JSON.stringify(Object.fromEntries(form.entries())) }); const replies = (result.messages || []).map((item) => item.text).join("\n\n"); $("#commandResult").textContent = replies || `Command completed. Confirmation sent to chat ${result.deliveredToChatId}.`; await loadDashboard(); } catch (error) { $("#commandResult").textContent = error.message; } });
loadDashboard().then(() => showAuthenticated(true)).catch((error) => { if (error.status === 401) showAuthenticated(false); else { showAuthenticated(false); $("#loginError").textContent = error.message; } });
